<?php
return [
    'adminEmail' => 'admin@example.com',
    // this is for AdminLTE
    // https://www.yiiframework.com/extension/hail812/yii2-adminlte3
    'hail812/yii2-adminlte3' => [
        'pluginMap' => [
            'sweetalert2' => [
                'css' => 'sweetalert2-theme-bootstrap-4/bootstrap-4.min.css',
                'js' => 'sweetalert2/sweetalert2.min.js'
            ],
            'toastr' => [
                'css' => ['toastr/toastr.min.css'],
                'js' => ['toastr/toastr.min.js']
            ],
        ]
    ],
    'bsVersion' => '4.x',
    'avatars' => [
        0  => 'images/avatars/000.png',
        1  => 'images/avatars/001.png',
        2  => 'images/avatars/002.png',
        3  => 'images/avatars/003.png',
        4  => 'images/avatars/004.png',
        5  => 'images/avatars/005.png',
        6  => 'images/avatars/006.png',
        7  => 'images/avatars/007.png',
        8  => 'images/avatars/008.png',
        9  => 'images/avatars/009.png',
        10 => 'images/avatars/010.png',
        11 => 'images/avatars/011.png',
        12 => 'images/avatars/012.png',
        13 => 'images/avatars/013.png',
        14 => 'images/avatars/014.png',
        15 => 'images/avatars/015.png',
        16 => 'images/avatars/016.png',
        17 => 'images/avatars/017.png',
        18 => 'images/avatars/018.png',
        19 => 'images/avatars/019.png',
        20 => 'images/avatars/020.png',
        21 => 'images/avatars/021.png',
        22 => 'images/avatars/022.png',
        23 => 'images/avatars/023.png',
        24 => 'images/avatars/024.png',
        25 => 'images/avatars/025.png',
        26 => 'images/avatars/026.png',
        27 => 'images/avatars/027.png',
        28 => 'images/avatars/028.png',
        29 => 'images/avatars/029.png',
        30 => 'images/avatars/030.png',
        31 => 'images/avatars/031.png',
        32 => 'images/avatars/032.png',
        33 => 'images/avatars/033.png',
        34 => 'images/avatars/034.png',
        35 => 'images/avatars/035.png',
        36 => 'images/avatars/036.png',
        37 => 'images/avatars/037.png',
        38 => 'images/avatars/038.png',
        39 => 'images/avatars/039.png',
        40 => 'images/avatars/040.png',
        41 => 'images/avatars/041.png',
        42 => 'images/avatars/042.png',
        43 => 'images/avatars/043.png',
        44 => 'images/avatars/044.png',
        45 => 'images/avatars/045.png',
        46 => 'images/avatars/046.png',
        47 => 'images/avatars/047.png',
        48 => 'images/avatars/048.png',
        49 => 'images/avatars/049.png',
        50 => 'images/avatars/050.png',
    ],
    'question_types' => [
        'short_text' => Yii::t('app', 'Short Text'),
        'paragraph' => Yii::t('app', 'Paragraph'),
        'multiple_choice' => Yii::t('app', 'Multiple Choice'),
        'checkbox' => Yii::t('app', 'Checkbox'),
        'drop_down_list' => Yii::t('app', 'Drop Down List'),
        'true_false' => Yii::t('app', 'True or False'),
        'date' => Yii::t('app', 'Date'),
        'email' => Yii::t('app', 'Email'),
        'number' => Yii::t('app', 'Number'),
        'time' => Yii::t('app', 'Time'),
        'url' => Yii::t('app', 'Url'),
    ],
    'question_types_es' => [
        'short_text' => 'Respuesta Corta',
        'paragraph' => 'Párrafo',
        'multiple_choice' => 'Opción Múltiple',
        'checkbox' => 'Casillas de Verificación',
        'drop_down_list' => 'Lista Desplegable',
        'true_false' => 'Falso o Verdadero',
        'date' => 'Fecha',
        'email' => 'Email',
        'number' => 'Número',
        'time' => 'Hora',
        'url' => 'Url',
    ],
];
