<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Module' => 'Acceder al Módulo',
    'Addresses' => 'Direcciones',
    'Are you sure you want to delete this item?' => '¿Estás seguro de que deseas eliminar este elemento?',
    'Asunto' => 'Asunto',
    'Biography' => 'Biografía',
    'Close' => 'Cerrar',
    'Company' => 'Compañía',
    'Contraseña' => 'Contraseña',
    'Correo Electrónico' => 'Correo Electrónico',
    'Create Address' => 'Crear Dirección',
    'Create Enrollment Message' => 'Crear Mensaje de Inscripción',
    'Create Profile' => 'Crear Perfil',
    'Create Profile Info' => 'Crear Información de Perfil',
    'Código de verificación' => 'Código de Verificación',
    'Delete' => 'Eliminar',
    'Edit personal info' => 'Editar Información Personal',
    'Enrollment Messages' => 'Mensajes de Inscripción',
    'Industry' => 'Industria',
    'Lesson: {title}' => 'Lección: {title}',
    'Lessons list of module {title}' => 'Lista de lecciones del módulo {title}',
    'Member' => 'Usuario',
    'Mensaje' => 'Mensaje',
    'Messages' => 'Mensajes',
    'Module' => 'Módulo',
    'My Bio' => 'Mi Biografía',
    'My birth date' => 'Mi Fecha de Nacimiento',
    'My occupation' => 'Mi Ocupación',
    'My personal info' => 'Mi Información Personal',
    'My phone number' => 'Mi Número de Teléfono',
    'New Message' => 'Nuevo Mensaje',
    'Nombre de Usuario' => 'Nombre de Usuario',
    'Nombres' => 'Nombres',
    'Not Visible' => 'No Visible',
    'Password reset token cannot be blank.' => 'El token de restablecimiento de contraseña no puede estar vacío.',
    'Profile Infos' => 'Información de Perfiles',
    'Profiles' => 'Perfiles',
    'Reset' => 'Restablecer',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Send' => 'Enviar',
    'Social Links' => 'Enlaces Sociales',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'There is no user with this email address.' => 'No existe un usuario con esta dirección de correo electrónico.',
    'Update' => 'Actualizar',
    'Update Address: {name}' => 'Actualizar Dirección: {name}',
    'Update Biography' => 'Actualizar Biografía',
    'Update Enrollment Message: {name}' => 'Actualizar Mensaje de Inscripción: {name}',
    'Update Personal Info' => 'Actualizar Información Personal',
    'Update Profile Info: {name}' => 'Actualizar Información del Perfil: {name}',
    'Update Profile: {name}' => 'Actualizar Perfil: {name}',
    'Update my bio' => 'Actualizar mi Biografía',
    'Update my personal info' => 'Actualizar mi Información Personal',
    'User fullname' => 'Nombre Completo del Usuario',
    'Verify email token cannot be blank.' => 'El token de verificación de correo no puede estar vacío.',
    'Visible' => 'Visible',
    'Website' => 'Sitio Web',
    'Wrong password reset token.' => 'Token de restablecimiento de contraseña incorrecto.',
    'Wrong verify email token.' => 'Token de verificación de correo incorrecto.',
];

